"""create algorithm tables

Revision ID: 0c90faa0378f
Revises: 6052c193a26a
Create Date: 2024-09-20 11:41:13.377954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c90faa0378f'
down_revision: Union[str, None] = '6052c193a26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_index(op.f('ix_algorithm_is_default'), 'algorithm', ['is_default'], unique=False)
    op.create_table('algorithm_pass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('algorithm_id', sa.Integer(), nullable=False),
    sa.Column('blocking_keys', sa.JSON(), nullable=False),
    sa.Column('evaluators', sa.JSON(), nullable=False),
    sa.Column('rule', sa.String(length=255), nullable=False),
    sa.Column('cluster_ratio', sa.Float(), nullable=False),
    sa.Column('kwargs', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mpi_blocking_key_key'), 'mpi_blocking_key', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mpi_blocking_key_key'), table_name='mpi_blocking_key')
    op.drop_table('algorithm_pass')
    op.drop_index(op.f('ix_algorithm_is_default'), table_name='algorithm')
    op.drop_table('algorithm')
    # ### end Alembic commands ###
