"""recreating mpi schema

Revision ID: 987a0f14f4d7
Revises: f5716ac94693
Create Date: 2024-09-25 15:48:52.771030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '987a0f14f4d7'
down_revision: Union[str, None] = 'f5716ac94693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpi_person',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('internal_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mpi_patient',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('external_patient_id', sa.String(length=255), nullable=True),
    sa.Column('external_person_id', sa.String(length=255), nullable=True),
    sa.Column('external_person_source', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['mpi_person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mpi_blocking_value',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('blockingkey', sa.SmallInteger(), nullable=False),
    sa.Column('value', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['mpi_patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_blocking_value_patient_key_value', 'mpi_blocking_value', ['patient_id', 'blockingkey', 'value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_blocking_value_patient_key_value', table_name='mpi_blocking_value')
    op.drop_table('mpi_blocking_value')
    op.drop_table('mpi_patient')
    op.drop_table('mpi_person')
    # ### end Alembic commands ###
