"""add reference_id to person and patient

Revision ID: fb1b1ba0ad1f
Revises: a30b8bbccfdf
Create Date: 2024-10-15 14:57:00.688268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb1b1ba0ad1f'
down_revision: Union[str, None] = 'a30b8bbccfdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpi_patient', sa.Column('reference_id', sa.Uuid(), nullable=False))
    op.add_column('mpi_person', sa.Column('reference_id', sa.Uuid(), nullable=False))
    op.drop_column('mpi_person', 'internal_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpi_person', sa.Column('internal_id', sa.CHAR(length=32), nullable=False))
    op.drop_column('mpi_person', 'reference_id')
    op.drop_column('mpi_patient', 'reference_id')
    # ### end Alembic commands ###
