site_name: !ENV [SITE_NAME, 'Record Linker documentation']
theme:
  name: "material"
  logo: assets/record-linker-logo.svg
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: custom
    accent: custom
extra_css:
  - stylesheets/custom.css
extra:
  generator: false
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:dibbs@cdc.gov
      name: Email
plugins:
  - mermaid2
markdown_extensions:
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - md_in_html
repo_name: CDCgov/RecordLinker
repo_url: https://github.com/CDCgov/RecordLinker
edit_uri: edit/main/docs/
docs_dir: "site"
nav:
  - "Home": "index.md"
  - "Getting Started": "getting-started.md"
  - "Reference":
    - "Application Configuration": "app-configuration.md"
    - "Algorithm Configuration": "algo-configuration.md"
  - "Explanation":
    - "Algorithm Design": "algo-design.md"
    - "Schema Design": "schema-design.md"
    - "Tuning": "tuning.md"
  - "API Docs": "api-docs.html"
