site_name: !ENV [SITE_NAME, 'RecordLinker Documentation']
theme:
  name: "material"
  icon:
    repo: fontawesome/brands/github
extra_css:
  - stylesheets/custom.css
plugins:
  - mermaid2
markdown_extensions:
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
repo_name: CDCgov/RecordLinker
repo_url: https://github.com/CDCgov/RecordLinker
edit_uri: edit/main/docs/
docs_dir: "site"
nav:
  - "Home": "index.md"
  - "Getting Started":
    - Installation: "installation.md"
    - Configuration: "configuration.md"
  - "User Guide":
    - Design: "design.md"
    - Reference: "reference.md"
  - "API Docs": "api-docs.html"
