# Use the official Python 3.11 slim image as the base
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy the scripts and data directories into the image
COPY scripts /app/scripts
COPY data /app/data

# Install Python dependencies
RUN pip install --no-cache-dir pandas requests