name: Build and push database images on a monthly schedule

on:
  schedule:
    # Run at 9:15 PM UTC every day   (2:15 PM PT)
    - cron: "15 21 * * *"
jobs:
  service-set-up:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        database: [postgres:17, mysql:8, mssql/server:2022-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Convert repository name to lowercase
        run: echo "REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and push db images to GHCR
        run: |
          # If mssql, use a slightly different strategy to determine source and target image
          if [[ "${{ matrix.database }}" == "mssql/server:2022-latest" ]]; then
            TARGET_IMAGE="ghcr.io/${{ env.REPO }}/mssql:2022-latest"
            SOURCE_IMAGE="mcr.microsoft.com/mssql/server:2022-latest"
          else
            TARGET_IMAGE="ghcr.io/${{ env.REPO }}/${{ matrix.database }}"
            SOURCE_IMAGE="${{ matrix.database }}"
          fi

          echo "Pulling latest and greatest image from GHCR for $SOURCE_IMAGE..."
            if docker pull "$SOURCE_IMAGE"; then
              docker tag "$SOURCE_IMAGE" "$TARGET_IMAGE"
              docker push "$TARGET_IMAGE"
              echo "Pushed $TARGET_IMAGE to GHCR."
            else
              echo "Failed to pull source image: $SOURCE_IMAGE" >&2
              exit 1
            fi
