name: check smoke tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  service-set-up:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        database: [postgres:17, mysql:8, mssql/server:2022-latest]

    steps:
      - name: Display the database
        run: echo ${{ matrix.database }}

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Convert repository name to lowercase
        run: echo "REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and push db images to GHCR if necessary
        run: |
          # If mssql, use a slightly different strategy
          if [[ "${{ matrix.database }}" == "mssql/server:2022-latest" ]]; then
            TARGET_IMAGE="ghcr.io/${{ env.REPO }}/mssql:2022-latest"
            SOURCE_IMAGE="mcr.microsoft.com/mssql/server:2022-latest"
          else
            TARGET_IMAGE="ghcr.io/${{ env.REPO }}/${{ matrix.database }}"
            SOURCE_IMAGE="${{ matrix.database }}"
          fi
          echo "$TARGET_IMAGE"
          echo "$SOURCE_IMAGE"

          # Check if the image exists in GHCR
          if ! docker pull "$TARGET_IMAGE" >/dev/null; then
            echo "Image not found in GHCR, pulling from source: $SOURCE_IMAGE..."
            if docker pull "$SOURCE_IMAGE"; then
              docker tag "$SOURCE_IMAGE" "$TARGET_IMAGE"
              docker push "$TARGET_IMAGE"
              echo "Pushed $TARGET_IMAGE to GHCR."
            else
              echo "Failed to pull source image: $SOURCE_IMAGE" >&2
              exit 1
            fi
          else
            echo "Image already exists in GHCR: $TARGET_IMAGE, skipping pull and push."
          fi

      # - name: Pull and push to GHCR if necessary
      #   run: |
      #     if ! docker pull ghcr.io/${{ env.REPO }}/postgres:17; then
      #       docker pull postgres:17
      #       docker tag postgres:17 ghcr.io/${{ env.REPO }}/postgres:17
      #       docker push ghcr.io/${{ env.REPO }}/postgres:17
      #     fi

      # - name: Pull and push mysql to GHCR if necessary
      #   run: |
      #     if ! docker pull ghcr.io/${{ env.REPO }}/mysql:8; then
      #       docker pull mysql:8
      #       docker tag mysql:8 ghcr.io/${{ env.REPO }}/mysql:8
      #       docker push ghcr.io/${{ env.REPO }}/mysql:8
      #     fi

      # - name: Pull and push mssql to GHCR if necessary
      #   run: |
      #     if ! docker pull ghcr.io/${{ env.REPO }}/mssql:2022-latest; then
      #       docker pull mcr.microsoft.com/mssql/server:2022-latest
      #       docker tag mcr.microsoft.com/mssql/server:2022-latest ghcr.io/${{ env.REPO }}/mssql:2022-latest
      #       docker push ghcr.io/${{ env.REPO }}/mssql:2022-latest
      #     fi

  smoke_tests:
    runs-on: ubuntu-latest
    needs: service-set-up

    strategy:
      matrix:
        database: [postgres, sqlite, mysql, sqlserver] # Matrix for database types

    services:
      postgres:
        image: ghcr.io/cdcgov/recordlinker/postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: pw

      mysql:
        image: ghcr.io/cdcgov/recordlinker/mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: pw

      sqlserver:
        image: ghcr.io/cdcgov/recordlinker/mssql:2022-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: "YourStrong!Passw0rd"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Convert repository name to lowercase
        run: echo "REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push RecordLinker image to GHCR if necessary
        run: |
          if ! docker pull ghcr.io/${{ env.REPO }}/rl-service:latest; then
            echo "RecordLinker image not found, building and pushing to GHCR"
            docker build -t ghcr.io/${{ env.REPO }}/rl-service:latest .
            docker push ghcr.io/${{ env.REPO }}/rl-service:latest
          else
            echo "RecordLinker image found, using cached image."
          fi

      - name: Start RecordLinker Service and Run Smoke Tests
        run: |
          if [[ "${{ matrix.database }}" == "postgres" ]]; then
            export DB_URI="postgresql+psycopg2://postgres:pw@localhost:5432/postgres"
          elif [[ "${{ matrix.database }}" == "sqlite" ]]; then
            export DB_URI="sqlite:///testdb.sqlite3"
          elif [[ "${{ matrix.database }}" == "mysql" ]]; then
            export DB_URI="mysql+pymysql://root:pw@localhost:3306/mysql"
          elif [[ "${{ matrix.database }}" == "sqlserver" ]]; then
            export DB_URI="mssql+pyodbc://sa:YourStrong!Passw0rd@localhost:1433/master?driver=ODBC+Driver+18+for+SQL+Server&TrustServerCertificate=yes"
          fi

          # Start Record Linker Service
          docker run -d --name rl-service \
            --network="host" \
            -e DB_URI=$DB_URI \
            ghcr.io/${{ env.REPO }}/rl-service:latest  # Use the cached image

          # Wait for the RL Service to be healthy
          TRIES=5
          COUNT=0
          until curl -s http://localhost:8080/ | grep "OK"; do
            echo "Waiting for RL Service to become healthy... Attempt $((COUNT+1)) of $TRIES"
            sleep 5
            COUNT=$((COUNT+1))
            if [ "$COUNT" -ge "$TRIES" ]; then
              echo "RL Service did not become healthy in time."
              exit 1
            fi
          done

          # Run smoke tests and print the response
          JSON_BODY_1='{"record": {"birth_date": "2013-11-07", "sex": "M", "identifiers":[{"value": "123456789", "type": "MR"}], "name":[{"family":"Shepard", "given":["John"]}]}}'
          JSON_BODY_2='{"algorithm": "dibbs-default", "record": {"birth_date": "2000-12-06", "sex": "M", "identifiers":[{"value": "9876543210", "type": "MR"}], "name":[{"family":"Smith", "given":["William"]}]}}'

          #basic tests
          RESPONSE_1=$(curl -s -X POST http://localhost:8080/link \
          -d "$JSON_BODY_1" \
          -H "Content-Type: application/json")

          echo "Response: $RESPONSE_1"
          echo "$RESPONSE_1" | jq -e '.prediction == "no_match"' 

          PERSON_REFERENCE_ID=$(echo "$RESPONSE_1" | jq -r '.person_reference_id')

          RESPONSE_2=$(curl -s -X POST http://localhost:8080/link \
          -d "$JSON_BODY_1" \
          -H "Content-Type: application/json")

          echo "Response: $RESPONSE_2"
          echo "$RESPONSE_2" | jq -e '.prediction == "match"'  
          echo "$RESPONSE_2" | jq -e --arg id "$PERSON_REFERENCE_ID" '.person_reference_id == $id'

          #enhanced tests
          RESPONSE_3=$(curl -s -X POST http://localhost:8080/link \
          -d "$JSON_BODY_2" \
          -H "Content-Type: application/json")

          echo "Response: $RESPONSE_3"
          echo "$RESPONSE_3" | jq -e '.prediction == "no_match"'  

          PERSON_REFERENCE_ID=$(echo "$RESPONSE_3" | jq -r '.person_reference_id')

          RESPONSE_4=$(curl -s -X POST http://localhost:8080/link \
          -d "$JSON_BODY_2" \
          -H "Content-Type: application/json")

          echo "Response: $RESPONSE_4"
          echo "$RESPONSE_4" | jq -e '.prediction == "match"' 
          echo "$RESPONSE_4" | jq -e --arg id "$PERSON_REFERENCE_ID" '.person_reference_id == $id'     

          #invalid tests
          RESPONSE_5=$(curl -s -X POST http://localhost:8080/link \
          -d '{"algorithm": "invalid", "record": {}}' \
          -H "Content-Type: application/json")

          echo "Response: $RESPONSE_5"
          echo "$RESPONSE_5" | grep -q "No algorithm found"
