name: check smoke tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  smoke_tests:
    runs-on: ubuntu-latest

    # TODO: modify smoke tests to cover multiple db types
    services:
      db:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pw
        ports:
          - 5432:5432

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build RecordLinker Docker Image
      run: |
        docker build -t rl-service-image .

    - name: Start RecordLinker Service and Run Smoke Tests
      run: |
        # Start Record Linker Service
        docker run -d --name rl-service \
          --network="host" \
          -e DB_URI="postgresql+psycopg2://postgres:pw@localhost:5432/postgres" \
          -p 8080:8080 \
          rl-service-image

        # Wait for the RL Service to be healthy
        TRIES=5
        COUNT=0
        until curl -s http://localhost:8080/ | grep "OK"; do
          echo "Waiting for RL Service to become healthy... Attempt $((COUNT+1)) of $TRIES"
          sleep 5
          COUNT=$((COUNT+1))
          if [ "$COUNT" -ge "$TRIES" ]; then
            echo "RL Service did not become healthy in time."
            exit 1
          fi
        done
      
        ./scripts/smoke_tests.sh http://localhost:8080
