name: Build RL Docker Image and Cache

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-rl-with-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha, mode=max
