name: "demo-package"
# This workflow manages the building and pushing of a new Docker image to ghcr.io
# when merging a pull request into demo

on:
  push:
    branches: [demo]

jobs:
  package:
    runs-on: ubuntu-latest

    permissions:
      id-token: "write"
      packages: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build number
        run: |
          build="b$(git rev-list --count HEAD)"
          echo "build: $build"
          echo "BUILD=$build" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set package name
        run: |
          repo_name=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')
          echo "PACKAGE_NAME=${repo_name}/demo" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ env.PACKAGE_NAME }}:latest
            ghcr.io/${{ env.PACKAGE_NAME }}:${{ env.BUILD }}
