name: "scan GHCR images for vulnerabilities"

on:
  schedule:
    # Run everyday at 03:00 Eastern
    - cron: "0 3 * * *"
  pull_request:
    branches: [main]

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create package name from repo name
        run: echo "PACKAGE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ env.PACKAGE_NAME }}:latest
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1  # Fail the job if vulnerabilities are found
          ignore-unfixed: true  # Only report confirmed CVEs
