name: "scan GHCR images for vulnerabilities"

on:
  schedule:
    # Run everyday at 03:00 Eastern
    - cron: "0 3 * * *"
  pull_request:
    branches: [main]

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true

      - name: Create package name from repo name
        run: echo "PACKAGE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/{{ env.PACKAGE_NAME }}:v25.5.0
          format: table
          exit-code: 1  # Fail the job if vulnerabilities are found
          ignore-unfixed: true  # Only report confirmed CVEs
